apiVersion: v1
kind: Service

metadata:
  name: springboot-service

spec:
  selector:
    app: kubernatesexample-app

  ports:
  - protocol: TCP
    port: 1111
    targetPort: 1111
    nodePort: 31111

  type: NodePort