apiVersion: v1
kind: Service

metadata:
  name: springboot-service

spec:
  selector:
    app: kubernatesexample-testapp

  ports:
  - protocol: TCP
    port: 2222
    targetPort: 2222
    nodePort: 31000

  type: NodePort